#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
# Use IFS to set the field separator to ':'

# Open the /etc/passwd file for reading
myfile="/etc/passwd"

# Read each line of the file and extract the desired fields
while IFS=read -r line
do
  echo "$line" | cut -d":" -f1,3,6
# Close the file descriptor for /etc/passwd
done < "$myfile"
