#!/usr/bin/env bash

# Set counter variable
counter=1

# Loop while counter is less than 10
while [ $counter -le 10 ]
do
  # Display "Best School"
  echo "Best School"

  # Increment counter by 1
  ((counter++))
done
