#!/usr/bin/env bash
# A Bash script that displays: The content of the current directory

for file in *
do
  if [[ $file != .* && ! -d "$file" ]]; then
    filename=$(echo $file | cut -d '-' -f 2-)
    echo "$filename"
  fi
done
